### ISSUE TITLE
Install fails on macOS 11 with Xcode 12.1

### ISSUE THREAD

**Issue by kohenkatz** [postmodern/digest-crc#23]
I got the following error trying to run `bundle install` on a Fastlane project:

```
An error occurred while installing digest-crc (0.6.1), and Bundler cannot
continue.
Make sure that `gem install digest-crc -v '0.6.1' --source
'https://rubygems.org/'` succeeds before bundling.
In Gemfile:
  xcode-install was resolved to 2.6.7, which depends on
    fastlane was resolved to 2.167.0, which depends on
      google-cloud-storage was resolved to 1.29.1, which depends on
        digest-crc
```

I tried to run `sudo gem install digest-crc -v '0.6.1' --source 'https://rubygems.org/'` as it says, and I got this error:

```
Building native extensions. This could take a while...
ERROR:  Error installing digest-crc:
        ERROR: Failed to build gem native extension.

    current directory: /Library/Ruby/Gems/2.6.0/gems/digest-crc-0.6.1/ext/digest
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby -rrubygems /Library/Ruby/Gems/2.6.0/gems/rake-13.0.1/exe/rake RUBYARCHDIR\=/Library/Ruby/Gems/2.6.0/extensions/universal-darwin-20/2.6.0/digest-crc-0.6.1 RUBYLIBDIR\=/Library/Ruby/Gems/2.6.0/extensions/universal-darwin-20/2.6.0/digest-crc-0.6.1
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby -S extconf.rb
checking for stdint.h... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/$(RUBY_BASE_NAME)
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:467:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:585:in `block in try_compile'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:534:in `with_werror'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:585:in `try_compile'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:1109:in `block in have_header'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:959:in `block in checking_for'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:361:in `block (2 levels) in postpone'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:331:in `open'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:361:in `block in postpone'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:331:in `open'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:357:in `postpone'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:958:in `checking_for'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:1108:in `have_header'
        from extconf.rb:3:in `<main>'
rake aborted!
Command failed with status (1): [/System/Library/Frameworks/Ruby.framework/...]
/Library/Ruby/Gems/2.6.0/gems/digest-crc-0.6.1/ext/digest/Rakefile:32:in `block (3 levels) in <top (required)>'
/Library/Ruby/Gems/2.6.0/gems/digest-crc-0.6.1/ext/digest/Rakefile:31:in `chdir'
/Library/Ruby/Gems/2.6.0/gems/digest-crc-0.6.1/ext/digest/Rakefile:31:in `block (2 levels) in <top (required)>'
/Library/Ruby/Gems/2.6.0/gems/rake-13.0.1/exe/rake:27:in `<main>'
Tasks: TOP => default => crc16_genibus/crc16_genibus_ext.bundle => crc16_genibus/Makefile
(See full trace by running task with --trace)

rake failed, exit code 1

Gem files will remain installed in /Library/Ruby/Gems/2.6.0/gems/digest-crc-0.6.1 for inspection.
Results logged to /Library/Ruby/Gems/2.6.0/extensions/universal-darwin-20/2.6.0/digest-crc-0.6.1/gem_make.out
```

This was working last week, and the only change on this machine is that it got updated (against my will) to macOS 11 Big Sur.

It has been a very long time since I've worked with Ruby (other than Fastlane), so I'm not really sure where to start looking to see what the problem is.

**Comment by kohenkatz** [comment]
I just found that it works properly with 12.2, so I'm just going to switch to the newer one.
